const formatNumber = (value, decimals = 3) => {
  const numberValue = Number(value || 0)

  return numberValue.toLocaleString(undefined, {
    minimumFractionDigits: decimals,
    maximumFractionDigits: decimals,
  })
}

const formatPercent = (value) => {
  return `${formatNumber(value, 4)}%`
}

const getValue = (...values) => {
  for (const value of values) {
    if (value !== null && value !== undefined && String(value).trim() !== '') {
      return value
    }
  }

  return '-'
}

const getVarianceClass = (value) => {
  const numberValue = Number(value || 0)

  if (numberValue === 0) {
    return 'neutral'
  }

  if (numberValue < 0) {
    return 'negative'
  }

  return 'positive'
}

function ReportInfoCell({ label, value }) {
  return (
    <div className="mtr-info-cell">
      <span>{label}</span>
      <strong>{value}</strong>
    </div>
  )
}

function SealStatus({ status }) {
  const isOk = status === 'MATCHED' || status === 'NOT_ENTERED'

  return (
    <span className={`mtr-seal-status ${isOk ? 'ok' : 'bad'}`}>
      {status || '-'}
    </span>
  )
}

function TankerMtrComparisonReport({ group, generatedBy = '' }) {
  if (!group) {
    return null
  }

  const sender = group.senderTicket
  const receiver = group.latestReceiverTicket
  const comparison = group.quantityComparison

  const generatedAt = new Date().toLocaleString()

  return (
    <div className="tanker-mtr-report">
      <div className="mtr-report-header">
        <div>
          <h1>TANKER MTR / RECONCILIATION REPORT</h1>
          <p>Sender vs Receiver Quantity / Seal Comparison</p>
        </div>

        <div className="mtr-report-meta">
          <span>Generated At</span>
          <strong>{generatedAt}</strong>
          {generatedBy && (
            <>
              <span>Generated By</span>
              <strong>{generatedBy}</strong>
            </>
          )}
        </div>
      </div>

      <div className="mtr-status-strip">
        <div>
          <span>Convoy Number</span>
          <strong>{group.convoyNumber || '-'}</strong>
        </div>

        <div>
          <span>Tracking Status</span>
          <strong>{group.trackingStatus || '-'}</strong>
        </div>

        <div>
          <span>Product</span>
          <strong>{group.productName || '-'}</strong>
        </div>

        <div>
          <span>Tanker</span>
          <strong>
            {group.tankerAssetName || '-'} ({group.tankerAssetCode || '-'})
          </strong>
        </div>

        <div>
          <span>Chassis</span>
          <strong>{group.tankerChassisNumber || '-'}</strong>
        </div>

        <div>
          <span>Prime Mover</span>
          <strong>
            {group.primeMoverAssetName || '-'} (
            {group.primeMoverAssetCode || '-'})
          </strong>
        </div>
      </div>

      <div className="mtr-section">
        <h2>Ticket Details</h2>

        <div className="mtr-info-grid">
          <ReportInfoCell
            label="Sender Ticket"
            value={getValue(sender?.ticketNumber, sender?.operationNumber)}
          />
          <ReportInfoCell
            label="Sender Operation"
            value={getValue(sender?.operationTypeName, sender?.operationTypeCode)}
          />
          <ReportInfoCell
            label="Sender Date"
            value={getValue(sender?.operationDate)}
          />
          <ReportInfoCell
            label="Sender Location"
            value={`${getValue(
              sender?.originLocationName,
              sender?.originLocationCode
            )} (${getValue(sender?.originLocationCode)})`}
          />

          <ReportInfoCell
            label="Receiver Ticket"
            value={getValue(receiver?.ticketNumber, receiver?.operationNumber)}
          />
          <ReportInfoCell
            label="Receiver Operation"
            value={getValue(
              receiver?.operationTypeName,
              receiver?.operationTypeCode
            )}
          />
          <ReportInfoCell
            label="Receiver Date"
            value={getValue(receiver?.operationDate)}
          />
          <ReportInfoCell
            label="Receiver Location"
            value={`${getValue(
              receiver?.originLocationName,
              receiver?.originLocationCode
            )} (${getValue(receiver?.originLocationCode)})`}
          />
        </div>
      </div>

      <div className="mtr-two-column">
        <div className="mtr-section">
          <h2>Dip / Quality Comparison</h2>

          <table className="mtr-table mtr-compact-table">
            <thead>
              <tr>
                <th>Parameter</th>
                <th>Sender</th>
                <th>Receiver</th>
                <th>Diff.</th>
              </tr>
            </thead>

            <tbody>
              <tr>
                <td>Total Dip</td>
                <td>{sender ? `${formatNumber(sender.totalDipCm, 1)} cm` : '-'}</td>
                <td>
                  {receiver ? `${formatNumber(receiver.totalDipCm, 1)} cm` : '-'}
                </td>
                <td>
                  {sender && receiver
                    ? `${formatNumber(
                        receiver.totalDipCm - sender.totalDipCm,
                        1
                      )} cm`
                    : '-'}
                </td>
              </tr>

              <tr>
                <td>Water Dip</td>
                <td>{sender ? `${formatNumber(sender.waterDipCm, 1)} cm` : '-'}</td>
                <td>
                  {receiver ? `${formatNumber(receiver.waterDipCm, 1)} cm` : '-'}
                </td>
                <td>
                  {sender && receiver
                    ? `${formatNumber(
                        receiver.waterDipCm - sender.waterDipCm,
                        1
                      )} cm`
                    : '-'}
                </td>
              </tr>

              <tr>
                <td>BS&W</td>
                <td>{sender ? `${formatNumber(sender.bswPercent, 2)} %` : '-'}</td>
                <td>
                  {receiver ? `${formatNumber(receiver.bswPercent, 2)} %` : '-'}
                </td>
                <td>
                  {sender && receiver
                    ? `${formatNumber(
                        receiver.bswPercent - sender.bswPercent,
                        2
                      )} %`
                    : '-'}
                </td>
              </tr>

              <tr>
                <td>Tank Temp.</td>
                <td>
                  {sender
                    ? `${formatNumber(sender.tankTemperature, 2)} ${
                        sender.tankTemperatureUnit || ''
                      }`
                    : '-'}
                </td>
                <td>
                  {receiver
                    ? `${formatNumber(receiver.tankTemperature, 2)} ${
                        receiver.tankTemperatureUnit || ''
                      }`
                    : '-'}
                </td>
                <td>-</td>
              </tr>

              <tr>
                <td>API @ 60</td>
                <td>
                  {sender?.api60 !== null && sender?.api60 !== undefined
                    ? formatNumber(sender.api60, 2)
                    : '-'}
                </td>
                <td>
                  {receiver?.api60 !== null && receiver?.api60 !== undefined
                    ? formatNumber(receiver.api60, 2)
                    : '-'}
                </td>
                <td>
                  {sender?.api60 !== null &&
                  sender?.api60 !== undefined &&
                  receiver?.api60 !== null &&
                  receiver?.api60 !== undefined
                    ? formatNumber(receiver.api60 - sender.api60, 2)
                    : '-'}
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="mtr-section">
          <h2>Quantity Comparison</h2>

          {comparison ? (
            <table className="mtr-table mtr-quantity-table mtr-compact-table">
              <thead>
                <tr>
                  <th>Qty</th>
                  <th>Sender</th>
                  <th>Receiver</th>
                  <th>Var.</th>
                  <th>%</th>
                </tr>
              </thead>

              <tbody>
                <tr>
                  <td>GOV</td>
                  <td>{formatNumber(comparison.senderGovBbl)} bbl</td>
                  <td>{formatNumber(comparison.receiverGovBbl)} bbl</td>
                  <td className={getVarianceClass(comparison.govVarianceBbl)}>
                    {formatNumber(comparison.govVarianceBbl)}
                  </td>
                  <td>-</td>
                </tr>

                <tr>
                  <td>GSV</td>
                  <td>{formatNumber(comparison.senderGsvBbl)} bbl</td>
                  <td>{formatNumber(comparison.receiverGsvBbl)} bbl</td>
                  <td className={getVarianceClass(comparison.gsvVarianceBbl)}>
                    {formatNumber(comparison.gsvVarianceBbl)}
                  </td>
                  <td>-</td>
                </tr>

                <tr>
                  <td>NSV</td>
                  <td>{formatNumber(comparison.senderNsvBbl)} bbl</td>
                  <td>{formatNumber(comparison.receiverNsvBbl)} bbl</td>
                  <td className={getVarianceClass(comparison.nsvVarianceBbl)}>
                    {formatNumber(comparison.nsvVarianceBbl)}
                  </td>
                  <td>{formatPercent(comparison.nsvVariancePercent)}</td>
                </tr>

                <tr>
                  <td>LT</td>
                  <td>{formatNumber(comparison.senderLt)}</td>
                  <td>{formatNumber(comparison.receiverLt)}</td>
                  <td className={getVarianceClass(comparison.ltVariance)}>
                    {formatNumber(comparison.ltVariance)}
                  </td>
                  <td>-</td>
                </tr>

                <tr>
                  <td>MT</td>
                  <td>{formatNumber(comparison.senderMt)}</td>
                  <td>{formatNumber(comparison.receiverMt)}</td>
                  <td className={getVarianceClass(comparison.mtVariance)}>
                    {formatNumber(comparison.mtVariance)}
                  </td>
                  <td>-</td>
                </tr>
              </tbody>
            </table>
          ) : (
            <div className="info-box">
              Quantity comparison is available only after the receiver ticket is
              Approved.
            </div>
          )}
        </div>
      </div>

      <div className="mtr-section">
        <h2>Seal Cross-check</h2>

        <table className="mtr-table">
          <thead>
            <tr>
              <th>Seal</th>
              <th>Sender</th>
              <th>Receiver</th>
              <th>Status</th>
            </tr>
          </thead>

          <tbody>
            {(group.sealChecks || []).map((seal) => (
              <tr key={seal.sealName}>
                <td>{seal.sealName}</td>
                <td>{seal.senderValue || '-'}</td>
                <td>{seal.receiverValue || '-'}</td>
                <td>
                  <SealStatus status={seal.status} />
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="mtr-section">
        <h2>Remarks</h2>

        <div className="mtr-remarks-grid">
          <div>
            <span>Sender Remarks</span>
            <p>{sender?.remarks || '-'}</p>
          </div>

          <div>
            <span>Receiver Remarks</span>
            <p>{receiver?.remarks || '-'}</p>
          </div>

          <div>
            <span>Acknowledgement Remarks</span>
            <p>{group.acknowledgementRemarks || '-'}</p>
          </div>
        </div>
      </div>

      <div className="mtr-signature-grid">
        <div>
          <strong>Prepared By</strong>
          <span>Name / Signature / Date</span>
        </div>

        <div>
          <strong>Sender Representative</strong>
          <span>Name / Signature / Date</span>
        </div>

        <div>
          <strong>Receiver Representative</strong>
          <span>Name / Signature / Date</span>
        </div>

        <div>
          <strong>Approved By</strong>
          <span>Name / Signature / Date</span>
        </div>
      </div>
    </div>
  )
}

export default TankerMtrComparisonReport
